-- Table: fifa.players_data

-- DROP TABLE IF EXISTS fifa.players_data;

CREATE TABLE IF NOT EXISTS fifa.players_data
(
    sofifa_id integer,
    player_url text COLLATE pg_catalog."default",
    short_name text COLLATE pg_catalog."default",
    long_name text COLLATE pg_catalog."default",
    player_positions text COLLATE pg_catalog."default",
    overall integer,
    potential integer,
    value_eur double precision,
    wage_eur double precision,
    age integer,
    dob date,
    height_cm integer,
    weight_kg integer,
    club_team_id integer,
    club_name text COLLATE pg_catalog."default",
    league_name text COLLATE pg_catalog."default",
    league_level integer,
    club_position text COLLATE pg_catalog."default",
    club_jersey_number integer,
    club_loaned_from text COLLATE pg_catalog."default",
    club_joined text COLLATE pg_catalog."default",
    club_contract_valid_until text COLLATE pg_catalog."default",
    nationality_id integer,
    nationality_name text COLLATE pg_catalog."default",
    nation_team_id integer,
    nation_position text COLLATE pg_catalog."default",
    nation_jersey_number integer,
    preferred_foot text COLLATE pg_catalog."default",
    weak_foot integer,
    skill_moves integer,
    international_reputation integer,
    work_rate text COLLATE pg_catalog."default",
    body_type text COLLATE pg_catalog."default",
    real_face boolean,
    release_clause_eur text COLLATE pg_catalog."default",
    player_tags text COLLATE pg_catalog."default",
    player_traits text COLLATE pg_catalog."default",
    pace integer,
    shooting integer,
    passing integer,
    dribbling integer,
    defending integer,
    physic integer,
    attacking_crossing integer,
    attacking_finishing integer,
    attacking_heading_accuracy integer,
    attacking_short_passing integer,
    attacking_volleys integer,
    skill_dribbling integer,
    skill_curve integer,
    skill_fk_accuracy integer,
    skill_long_passing integer,
    skill_ball_control integer,
    movement_acceleration integer,
    movement_sprint_speed integer,
    movement_agility integer,
    movement_reactions integer,
    movement_balance integer,
    power_shot_power integer,
    power_jumping integer,
    power_stamina integer,
    power_strength integer,
    power_long_shots integer,
    mentality_aggression integer,
    mentality_interceptions integer,
    mentality_positioning integer,
    mentality_vision integer,
    mentality_penalties integer,
    mentality_composure text COLLATE pg_catalog."default",
    defending_marking_awareness integer,
    defending_standing_tackle integer,
    defending_sliding_tackle integer,
    goalkeeping_diving integer,
    goalkeeping_handling integer,
    goalkeeping_kicking integer,
    goalkeeping_positioning integer,
    goalkeeping_reflexes integer,
    goalkeeping_speed integer,
    ls text COLLATE pg_catalog."default",
    st text COLLATE pg_catalog."default",
    rs text COLLATE pg_catalog."default",
    lw text COLLATE pg_catalog."default",
    lf text COLLATE pg_catalog."default",
    cf text COLLATE pg_catalog."default",
    rf text COLLATE pg_catalog."default",
    rw text COLLATE pg_catalog."default",
    lam text COLLATE pg_catalog."default",
    cam text COLLATE pg_catalog."default",
    ram text COLLATE pg_catalog."default",
    lm text COLLATE pg_catalog."default",
    lcm text COLLATE pg_catalog."default",
    cm text COLLATE pg_catalog."default",
    rcm text COLLATE pg_catalog."default",
    rm text COLLATE pg_catalog."default",
    lwb text COLLATE pg_catalog."default",
    ldm text COLLATE pg_catalog."default",
    cdm text COLLATE pg_catalog."default",
    rdm text COLLATE pg_catalog."default",
    rwb text COLLATE pg_catalog."default",
    lb text COLLATE pg_catalog."default",
    lcb text COLLATE pg_catalog."default",
    cb text COLLATE pg_catalog."default",
    rcb text COLLATE pg_catalog."default",
    rb text COLLATE pg_catalog."default",
    gk text COLLATE pg_catalog."default",
    player_face_url text COLLATE pg_catalog."default",
    club_logo_url text COLLATE pg_catalog."default",
    club_flag_url text COLLATE pg_catalog."default",
    nation_logo_url text COLLATE pg_catalog."default",
    nation_flag_url text COLLATE pg_catalog."default",
    year integer,
    sex text COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS fifa.players_data
    OWNER to fifaproject;